name: Bug report
description: Found a bug? Report it here!
title: '[Bug] '
assignees:
  - greeeen-dev
labels:
  - bug
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please make sure all of the following applies to your issue.
      options:
        - label: I've checked issues to see if my bug has been reported yet.
          required: true
        - label: My issue is only reproducible with Natsumi Browser installed.
          required: true
        - label: My installation of Natsumi Browser was not modified whatsoever.
          required: true
        - label: My issue is reproducible without Floorp Mods or additional CSS applied.
          required: true
        - label: I've provided as much info/evidence as I can.
          required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What Natsumi Browser version did you use when you encountered the bug?
      placeholder: 1.6.2, 2.0.0, etc.
    validations:
      required: true
  - type: input
    id: floorpversion
    attributes:
      label: Floorp Browser Version
      description: What Floorp Browser version did you use when you encountered the bug?
      placeholder: 1.7.1b, 1.7.2t, etc.
    validations:
      required: true
  - type: textarea
    id: bug-desc
    attributes:
      label: Bug description
      description: Please provide a clear and concise description of what the bug is.
      placeholder: >-
        e.g. "The Print and Save file icons on the PDF viewer won't display properly on dark mode."
    validations:
      required: true
  - type: textarea
    id: bug-repro
    attributes:
      label: Reproduction steps
      description: What should we do to reproduce the bug?
      placeholder: e.g. 1. Open PDF viewer 2. Icons are not displayed
    validations:
      required: true
  - type: textarea
    id: bug-expected
    attributes:
      label: Expected behavior
      description: What should've happened instead?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If you have screenshots of the bug, please attach them here.
  - type: markdown
    attributes:
      value: <p>
        Please do not report false bugs to us. On repeated false reports, we may prevent you from creating new issues on the repository.
